### ISSUE TITLE
Logarithmic slider?

### ISSUE THREAD

**Issue by mccalluc** [opendp/dp-creator-ii#25]
For epsilon, the mockups have a slider that goes from 0.1 to 10.0, with 1.0 in the middle. How feasible is this with Shiny?

**Comment by cmbz** [comment]
Have you taken a look at the Shiny components gallery: https://shiny.posit.co/py/components/. There are several sliders that might work.

**Comment by mccalluc** [comment]
I only see two slider components: One is plain; the other selects a range. For neither do I see any option for anything other than a linear scale: We can't supply a function to rescale values. It looks like R shiny has a slider that lets you choose between a few distinct values, but it doesn't exist on the python side.

This isn't a blocker right now. If there's not a better solution, could imagine copy and pasting Shiny source code, and tweaking to match our needs.
