### ISSUE TITLE
Whisker plot, with a dashed line for delta

### ISSUE THREAD

**Issue by mccalluc** [opendp/dp-creator-ii#27]
Don't even worry about connecting it to any particular data, but just figure out which charting library to use to so we can have:
- whiskers on the bars
- dashed horizontal line across the full width
- perhaps grey-out the bars below that line
- no labels on vertical axis. (With mock data, the absolute number of counts wouldn't matter, so we don't want to label the axis.)

**Comment by cmbz** [comment]
One possibility? https://seaborn.pydata.org/generated/seaborn.boxplot.html
