### ISSUE TITLE
File upload selector

### ISSUE THREAD

**Issue by cmbz** [opendp/dp-creator-ii#92]
## Overview
- Design and implement the file upload selector

## Issues
- [x] https://github.com/opendp/dp-creator-ii/issues/81

## Dependencies
- None

## Related
- https://github.com/opendp/dp-creator-ii/issues/91

**Comment by mccalluc** [comment]
File upload is an off-the-shelf widget, so I think this is complete? If something more is required, please clarify and reopen.
