### ISSUE TITLE
Document project board state transisions

### ISSUE THREAD

**Issue by mccalluc** [opendp/dp-creator-ii#99]
https://github.com/orgs/opendp/projects/10

How do issues and PRs move between the columns? Who moves them, and what can be automated?

**Comment by cmbz** [comment]
@mccalluc and @ekraffmiller a few workflows have been turned on for the project: https://github.com/orgs/opendp/projects/10/workflows. You can review and edit to make sure they do what you expect.

Also, you will probably want to decide what actions happen for the [Code review approved](https://github.com/orgs/opendp/projects/10/workflows/782a9832-64e3-4e1d-b174-144e1b7947ac) and [Code changes requested](https://github.com/orgs/opendp/projects/10/workflows/d097d9d2-4e7a-4458-afb9-f0c93cb4cf87) workflows.
